# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            transform.forward
tagline:          // http://christopherhayward.me
description:      'The personal blog for Chris Hayward'
url:              http://christopherhayward.me

author:
  name:           'Chris Hayward'
  url:            https://twitter.com/ellji	

paginate:         5

# Custom vars
version:          2.0.0
