# Dependencies
# github has deprecated redcarpet as a markdown engin
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            transform.forward
tagline:          Opinions may change when observed.
description:      'The personal blog for <br>Chris Hayward.<br><br>Updated infrequently.'
url:              http://christopherhayward.me

author:
  name:           'Chris Hayward'
  url:            https://twitter.com/ellji	

paginate:         5

# Custom vars
twitter:
  handle:         https://twitter.com/ellji
github:
  repo:           https://github.com/ellji/
  
