# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               transform.forward
tagline:             // the personal blog for Chris Hayward
url:                 http://christopherhayward.me
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Chris Hayward
  url:               https://twitter.com/ellji

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
